# Site settings
title: "Glenn E. Bailey III"
description: "Resume/CV for Glenn E. Bailey III"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Glenn E. Bailey III"
resume_title:                   "Cloud Architect"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "glenn@dronemusic.co"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p>Automation architect and engineer that can research, analyze feasibility, develop, and deploy systems with a specialty in cloud environments.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       false
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/replicant0wnz"
  resume_twitter_url:           "https://twitter.com/replicant0wnz"
  resume_linkedin_url:          "https://www.linkedin.com/in/replicant"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://dronemusic.co/blog"
    #  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
